@extends('layouts.dashboundary')
@section('title')
Products
@endsection

@section('content')
@php
    $products = [
        ['name'=>'Green Cabbage','sku'=>'ECO-10021','category'=>'Fresh Vegetables','price'=>'৳ 80','stock'=>72,'featured'=>true,'image'=>'frontend/images/cabbage.png','date'=>'Today, 10:24 AM'],
        ['name'=>'Red Capsicum','sku'=>'ECO-10022','category'=>'Fresh Vegetables','price'=>'৳ 160','stock'=>18,'featured'=>true,'image'=>'frontend/images/capcicum.png','date'=>'Today, 9:40 AM'],
        ['name'=>'Fresh Mango','sku'=>'ECO-10023','category'=>'Fresh Fruit','price'=>'৳ 220','stock'=>45,'featured'=>false,'image'=>'frontend/images/fruits.png','date'=>'Yesterday'],
        ['name'=>'Atlantic Salmon','sku'=>'ECO-10024','category'=>'Meat & Fish','price'=>'৳ 890','stock'=>7,'featured'=>true,'image'=>'frontend/images/fish.png','date'=>'Yesterday'],
        ['name'=>'Farm Fresh Potato','sku'=>'ECO-10025','category'=>'Fresh Vegetables','price'=>'৳ 55','stock'=>0,'featured'=>false,'image'=>'frontend/images/potato.png','date'=>'Aug 12, 2026'],
        ['name'=>'Organic Corn','sku'=>'ECO-10026','category'=>'Fresh Vegetables','price'=>'৳ 120','stock'=>29,'featured'=>false,'image'=>'frontend/images/corn.png','date'=>'Aug 11, 2026'],
    ];
@endphp
<div class="manager-page">
    <div class="manager-heading d-flex flex-wrap justify-content-between align-items-center gap-3"><div><span class="eyebrow">CATALOG MANAGEMENT</span><h1>Products</h1><p>A clear view of every item in your storefront.</p></div><button class="btn btn-success manager-add" data-bs-toggle="modal" data-bs-target="#addProductModal"><i data-feather="plus"></i> Add product</button></div>
    <div class="row g-3 mb-4">
        <div class="col-sm-6 col-xl-3"><button class="metric-card active-filter w-100 text-start" data-filter="all"><span class="metric-icon green"><i data-feather="shopping-bag"></i></span><span><small>Total products</small><strong>{{ count($products) }}</strong><em>In your catalog</em></span></button></div>
        <div class="col-sm-6 col-xl-3"><button class="metric-card w-100 text-start" data-filter="featured"><span class="metric-icon amber"><i data-feather="star"></i></span><span><small>Featured</small><strong>{{ collect($products)->where('featured', true)->count() }}</strong><em>Priority placement</em></span></button></div>
        <div class="col-sm-6 col-xl-3"><button class="metric-card w-100 text-start" data-filter="low"><span class="metric-icon blue"><i data-feather="alert-circle"></i></span><span><small>Low stock</small><strong>{{ collect($products)->whereBetween('stock',[1,20])->count() }}</strong><em>Needs attention</em></span></button></div>
        <div class="col-sm-6 col-xl-3"><button class="metric-card w-100 text-start" data-filter="out"><span class="metric-icon purple"><i data-feather="clock"></i></span><span><small>Out of stock</small><strong>{{ collect($products)->where('stock', 0)->count() }}</strong><em>Hidden from sale</em></span></button></div>
    </div>
    <div class="card manager-table-card"><div class="card-body p-0"><div class="table-toolbar"><div class="search-box"><i data-feather="search"></i><input id="productSearch" type="search" placeholder="Search products or SKU..."></div><div class="toolbar-actions"><select id="productCategory" class="form-select"><option value="all">All categories</option><option value="fresh vegetables">Vegetables</option><option value="fresh fruit">Fruits</option><option value="meat & fish">Meat & Fish</option></select><button id="productFeatured" class="btn btn-outline-warning"><i data-feather="star"></i> Featured</button></div></div><div class="table-responsive"><table class="table manager-table mb-0"><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Featured</th><th>Added</th><th class="text-end">Action</th></tr></thead><tbody id="productRows">
    @foreach($products as $product)<tr data-name="{{ strtolower($product['name'].' '.$product['sku']) }}" data-category="{{ strtolower($product['category']) }}" data-featured="{{ $product['featured']?'yes':'no' }}" data-stock="{{ $product['stock'] }}"><td><div class="entity"><img class="table-image" src="{{ asset($product['image']) }}" alt=""><span><strong>{{ $product['name'] }}</strong><small>{{ $product['sku'] }}</small></span></div></td><td><span class="count-pill">{{ $product['category'] }}</span></td><td class="price-cell">{{ $product['price'] }}</td><td>@if($product['stock'] === 0)<span class="badge bg-light text-danger">Out of stock</span>@elseif($product['stock'] <= 20)<span class="stock-low">{{ $product['stock'] }} left</span>@else<span class="stock-good">{{ $product['stock'] }} in stock</span>@endif</td><td><button class="star-toggle {{ $product['featured'] ? 'is-featured' : '' }}"><i data-feather="star"></i></button></td><td class="muted-cell">{{ $product['date'] }}</td><td class="text-end"><button class="btn btn-light btn-sm table-action"><i data-feather="more-horizontal"></i></button></td></tr>@endforeach
    </tbody></table></div><div id="productEmpty" class="empty-state d-none"><i data-feather="search"></i><p>No products match your filters.</p></div></div></div>
</div>
<div class="modal fade" id="addProductModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered modal-lg"><form class="modal-content" onsubmit="event.preventDefault(); bootstrap.Modal.getInstance(document.getElementById('addProductModal')).hide();"><div class="modal-header"><div><span class="eyebrow">NEW PRODUCT</span><h4 class="mb-0">Add product</h4></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="row g-3"><div class="col-md-7"><label class="form-label">Product name</label><input required class="form-control" placeholder="e.g. Organic Green Tea"></div><div class="col-md-5"><label class="form-label">SKU</label><input class="form-control" placeholder="ECO-10027"></div><div class="col-md-6"><label class="form-label">Category</label><select class="form-select"><option>Fresh Vegetables</option><option>Fresh Fruit</option><option>Meat & Fish</option></select></div><div class="col-md-3"><label class="form-label">Price (৳)</label><input type="number" class="form-control" placeholder="0.00"></div><div class="col-md-3"><label class="form-label">Stock</label><input type="number" class="form-control" placeholder="0"></div><div class="col-12"><label class="form-label">Product image</label><input type="file" class="form-control" accept="image/*"></div><div class="col-12"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" id="product-featured"><label class="form-check-label" for="product-featured">Make this a featured product</label></div></div></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-success">Save product</button></div></form></div></div>
@include('backend.partials.manager-assets')
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const q=document.querySelector('#productSearch'),c=document.querySelector('#productCategory'),f=document.querySelector('#productFeatured'),e=document.querySelector('#productEmpty'),rs=[...document.querySelectorAll('#productRows tr')];let featured=false,metric='all';function draw(){let n=0;rs.forEach(r=>{const show=r.dataset.name.includes(q.value.toLowerCase())&&(c.value==='all'||r.dataset.category===c.value)&&(!featured||r.dataset.featured==='yes')&&(metric==='all'||metric==='featured'&&r.dataset.featured==='yes'||metric==='low'&&+r.dataset.stock>0&&+r.dataset.stock<=20||metric==='out'&&+r.dataset.stock===0);r.classList.toggle('d-none',!show);n+=show} );e.classList.toggle('d-none',!!n)}q.oninput=c.onchange=draw;f.onclick=()=>{featured=!featured;f.classList.toggle('active',featured);draw()};document.querySelectorAll('.metric-card').forEach(b=>b.onclick=()=>{metric=b.dataset.filter;document.querySelectorAll('.metric-card').forEach(x=>x.classList.toggle('active-filter',x===b));draw()});document.querySelectorAll('.star-toggle').forEach(b=>b.onclick=()=>{b.classList.toggle('is-featured');b.closest('tr').dataset.featured=b.classList.contains('is-featured')?'yes':'no';draw()});feather.replace()});</script>@endpush
@endsection
