@extends('layouts.dashboundary')
@section('title')
Registered Customer List
@endsection

@section('content')
<div class="manager-page">
    <div class="manager-heading d-flex flex-wrap justify-content-between align-items-center gap-3"><div><span class="eyebrow">CUSTOMER DIRECTORY</span><h1>Users</h1><p>Know your customers and keep your community growing.</p></div><button class="btn btn-success manager-add" data-bs-toggle="modal" data-bs-target="#addUserModal"><i data-feather="user-plus"></i> Add user</button></div>
    <div class="row g-3 mb-4">
        <div class="col-sm-6 col-xl-3"><button class="metric-card active-filter w-100 text-start" data-filter="all"><span class="metric-icon green"><i data-feather="users"></i></span><span><small>Total users</small><strong>{{ $users->count() }}</strong><em>Registered accounts</em></span></button></div>
        <div class="col-sm-6 col-xl-3"><button class="metric-card w-100 text-start" data-filter="new"><span class="metric-icon amber"><i data-feather="user-plus"></i></span><span><small>New this month</small><strong>{{ $users->filter(fn($user) => $user->created_at && $user->created_at->isSameMonth(now()))->count() }}</strong><em>Recently joined</em></span></button></div>
        <div class="col-sm-6 col-xl-3"><button class="metric-card w-100 text-start" data-filter="verified"><span class="metric-icon blue"><i data-feather="shield"></i></span><span><small>Verified</small><strong>{{ $users->whereNotNull('email_verified_at')->count() }}</strong><em>Email confirmed</em></span></button></div>
        <div class="col-sm-6 col-xl-3"><button class="metric-card w-100 text-start" data-filter="admin"><span class="metric-icon purple"><i data-feather="award"></i></span><span><small>Administrators</small><strong>1</strong><em>Store managers</em></span></button></div>
    </div>
    <div class="card manager-table-card"><div class="card-body p-0"><div class="table-toolbar"><div class="search-box"><i data-feather="search"></i><input id="userSearch" type="search" placeholder="Search name or email..."></div><div class="toolbar-actions"><select id="userStatus" class="form-select"><option value="all">All users</option><option value="verified">Verified</option><option value="unverified">Unverified</option></select><button id="newUsers" class="btn btn-outline-success"><i data-feather="user-plus"></i> New users</button></div></div><div class="table-responsive"><table class="table manager-table mb-0"><thead><tr><th>User</th><th>Role</th><th>Joined</th><th>Verification</th><th>Last activity</th><th class="text-end">Action</th></tr></thead><tbody id="userRows">
@forelse($users as $user)<tr data-name="{{ strtolower($user->name.' '.$user->email) }}" data-status="{{ $user->email_verified_at ? 'verified' : 'unverified' }}" data-new="{{ $user->created_at && $user->created_at->isSameMonth(now()) ? 'yes' : 'no' }}" data-role="{{ $user->id === auth()->id() ? 'admin' : 'customer' }}"><td><div class="entity"><img class="user-avatar" src="{{ $user->photo ? asset($user->photo) : asset('backend/img/avatars/avatar.jpg') }}" alt="{{ $user->name }}"><span><strong>{{ $user->name }}</strong><small>{{ $user->email }}</small></span></div></td><td><span class="role-pill">{{ $user->id === auth()->id() ? 'Administrator' : 'Customer' }}</span></td><td class="muted-cell">{{ optional($user->created_at)->format('M d, Y') ?? '—' }}</td><td>@if($user->email_verified_at)<span class="status-dot active">Verified</span>@else<span class="status-dot inactive">Pending</span>@endif</td><td class="muted-cell">{{ optional($user->updated_at)->diffForHumans() ?? '—' }}</td><td class="text-end"><button class="btn btn-light btn-sm table-action"><i data-feather="more-horizontal"></i></button></td></tr>
@empty<tr><td colspan="6"><div class="empty-state"><i data-feather="users"></i><p>No users have registered yet.</p></div></td></tr>@endforelse
</tbody></table></div><div id="userEmpty" class="empty-state d-none"><i data-feather="search"></i><p>No users match your filters.</p></div></div></div>
</div>
<div class="modal fade" id="addUserModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><form class="modal-content" onsubmit="event.preventDefault(); bootstrap.Modal.getInstance(document.getElementById('addUserModal')).hide();"><div class="modal-header"><div><span class="eyebrow">NEW ACCOUNT</span><h4 class="mb-0">Add user</h4></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">Full name</label><input required class="form-control" placeholder="Customer name"><label class="form-label mt-3">Email address</label><input required type="email" class="form-control" placeholder="name@example.com"><label class="form-label mt-3">Role</label><select class="form-select"><option>Customer</option><option>Administrator</option></select><label class="form-label mt-3">Temporary password</label><input required type="password" class="form-control" placeholder="Set a secure password"></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-success">Create user</button></div></form></div></div>
@include('backend.partials.manager-assets')
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const q=document.querySelector('#userSearch'),s=document.querySelector('#userStatus'),f=document.querySelector('#newUsers'),e=document.querySelector('#userEmpty'),rs=[...document.querySelectorAll('#userRows tr[data-name]')];let newOnly=false,metric='all';function draw(){let n=0;rs.forEach(r=>{const show=r.dataset.name.includes(q.value.toLowerCase())&&(s.value==='all'||r.dataset.status===s.value)&&(!newOnly||r.dataset.new==='yes')&&(metric==='all'||metric==='new'&&r.dataset.new==='yes'||metric==='verified'&&r.dataset.status==='verified'||metric==='admin'&&r.dataset.role==='admin');r.classList.toggle('d-none',!show);n+=show});e.classList.toggle('d-none',!!n)}q.oninput=s.onchange=draw;f.onclick=()=>{newOnly=!newOnly;f.classList.toggle('active',newOnly);draw()};document.querySelectorAll('.metric-card').forEach(b=>b.onclick=()=>{metric=b.dataset.filter;document.querySelectorAll('.metric-card').forEach(x=>x.classList.toggle('active-filter',x===b));draw()});feather.replace()});</script>@endpush
@endsection

